name: Build
# inspired from
# - https://github.com/android/nowinandroid/blob/main/.github/workflows/Build.yaml
on:
  push:
    branches: ["develop","main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Move Directory
        run: cd android

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Test Directory
        run: ls

      - name: Set Secret Properties
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
        run: echo "$SECRETS_PROPERTIES" > ./secrets.properties

      - name: Set google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > ./app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Update latest_develop tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        run : git tag -f latest_develop; git push -f --tags

      - name: Development release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        uses: marvinpinto/action-automatic-releases@v1.1.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest_develop
          title: "Latest development build"
          files: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/apk/debug/output-metadata.json
